name: Test Website 69
favicon: null
layout_spectrum: 0.15045636449940503
typography_spectrum: 0.27075433800928295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4923900219146162
  lightness: 0.44238678994588554
  saturation: 0.7984269885346293
  rhythmicContrast: 0.5814295150339603
purpose: []
