name: Test Website 69
favicon: null
layout_spectrum: 0.74849
typography_spectrum: 0.75837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#666666'
    - '#8cc63f'
    - '#e8515c'
    - '#ffffff'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.44238678994588554
  saturation: 0.7984269885346293
  rhythmicContrast: 0.5814295150339603
purpose: []
